- id: doi:10.1182/blood.2022018246
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006497123002355-BLOOD_BLD-2022-018246-fx1_lrg.jpg
  description: Single cell RNA sequencing analysis dissecting responses to ipilimumab treatment of relapsed AML/MDS with and without stem cell transplantation.
  tags:
   - scRNA-seq
   - AML
   - immunotherapy
   - stem cell transplantation
   
- id: doi:10.1158/2159-8290.CD-21-0276
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/11/12/10.1158_2159-8290.cd-11-12-iti/1/m_2945photo4.jpeg
  description: First demonstration that longitudinal changes of mitochondrial DNA mutations reflect therapeutic bottlenecks. 
  tags:
   - mtDNA mutations
   - lineage-tracing
   - CLL
   - clonal evolution

- id: doi:10.1182/blood.2022017686
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/issue/141/15/4/m_bloodjournal_141_15.cover.png
  
- id: doi:10.1158/2643-3230.BCD-22-0082
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/bloodcancerdiscov/issue/4/2/1/m_bloodcandisc_4_2_cover.png
  
- id: doi:10.1158/0008-5472.CAN-22-0275
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/83/5/4/m_canres_83_5_cover.png
  
- id: doi:10.1158/2326-6066.CIR-22-0434
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerimmunolres/issue/10/11/2/m_canimm_10_11_cover.png
  
- id: doi:10.1182/blood.2022017614
  image: https://ashpublications.org/view-large/figure/10721289/bloodBLD2022017614Cf1.tif
  
- id: doi:10.1016/j.jcyt.2022.03.005
  image: https://www.isct-cytotherapy.org/cms/asset/48861aee-60b3-4a88-b830-db00215fa312/gr1.sml

- id: doi:10.1158/1078-0432.CCR-21-2834
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/28/15/2/m_clincanres_28_15_cover.png
  
- id: doi:10.3389/fimmu.2021.788891
  image: https://www.frontiersin.org/files/Articles/788891/fimmu-12-788891-HTML/image_m/fimmu-12-788891-g001.jpg

- id: doi:10.1182/bloodadvances.2021004335
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/bloodadvances/5/22/10.1182_bloodadvances.2021004335/4/advancesadv2021004335absf1.png
  
- id: doi:10.1182/blood.2021010867
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/137/23/10.1182_blood.2021010867/5/bloodbld2021010867absf1.png
  
- id: doi:10.1172/JCI129209
  image: https://dm5migu4zj3pb.cloudfront.net/manuscripts/129000/129209/medium/JCI129209.f1.jpg
