- id: doi:10.1182/blood.2022018246
  type: paper
  date: 2023-04-13
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006497123002355-BLOOD_BLD-2022-018246-fx1_lrg.jpg
  description: Single cell RNA sequencing analysis dissecting responses to ipilimumab treatment of relapsed AML/MDS with and without stem cell transplantation.
  tags:
   - scRNA-seq
   - AML
   - immunotherapy
   - stem cell transplantation
   
- id: doi:10.1158/2159-8290.CD-21-0276
  type: paper
  date: 2021-12-01
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/11/12/10.1158_2159-8290.cd-11-12-iti/1/m_2945photo4.jpeg
  description: First demonstration that longitudinal changes of mitochondrial DNA mutations reflect therapeutic bottlenecks. 
  tags:
   - mtDNA mutations
   - lineage-tracing
   - CLL
   - clonal evolution

- id: doi:10.1182/blood.2022017686
  type: paper
  image: https://ashpublications.org/view-large/figure/11655499/BLOOD_BLD-2022-017686-gr1.jpg
  
- id: doi:10.1158/2643-3230.BCD-22-0082
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/bloodcancerdiscov/issue/4/2/1/m_bloodcandisc_4_2_cover.png
  
- id: doi:10.1158/0008-5472.CAN-22-0275
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/83/5/4/m_canres_83_5_cover.png
  
- id: doi:10.1158/2326-6066.CIR-22-0434
  type: paper
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerimmunolres/issue/10/11/2/m_canimm_10_11_cover.png
  
