- id: doi:10.1182/blood.2022018246
  type: paper
  date: 2023-04-13
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0006497123002355-BLOOD_BLD-2022-018246-fx1_lrg.jpg
  description: Single cell RNA sequencing analysis dissecting responses to ipilimumab treatment of relapsed AML/MDS with and without stem cell transplantation.
  tags:
   - scRNA-seq
   - AML
   - immunotherapy
   - stem cell transplantation
   
- id: doi:10.1158/2159-8290.CD-21-0276
  type: paper
  date: 2021-12-01
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerdiscovery/11/12/10.1158_2159-8290.cd-11-12-iti/1/m_2945photo4.jpeg
  description: First demonstration that longitudinal changes of mitochondrial DNA mutations reflect therapeutic bottlenecks. 
  tags:
   - mtDNA mutations
   - lineage-tracing
   - CLL
   - clonal evolution
